# -*- coding: utf-8 -*-
"""Задание 3 со звездочкой.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1djr4eXpgqX-PESsuBUP59n3jRjhrGnlP
"""

a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

for i in range(1,100000000000000000000):
  if i % a[0] == 0 and i % a[1] == 0 and i % a[2] == 0 and i % a[3] == 0 and i % a[4] == 0 and i % a[5] == 0 and i % a[6] == 0 and i % a[7] == 0 and i % a[8] == 0 and i % a[9] == 0 and i % a[10] == 0 and i % a[11] == 0 and i % a[12] == 0 and i % a[13] == 0 and i % a[14] == 0 and i % a[15] == 0 and i % a[16] == 0 and i % a[17] == 0 and i % a[18] == 0 and i % a[19] == 0:
    break
print(i)