# -*- coding: utf-8 -*-
"""Задание 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dj6fx_ehwFklNKZJJYDFM9YMD6ywnqtB
"""

first_number = input('Введите первое число: ')
second_number = input('Введите второе число: ')
if int(first_number) > int(second_number):
  print('True'),
else:
  print('False')