# -*- coding: utf-8 -*-
"""Задание_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQmB8vgZHDWSU7AxgDrhRcMFAGremFDw
"""

word = input()
if word == word[::-1]:
  print('Палиндром'),
elif word != word[::-1]:
  print('Не палиндром')