# -*- coding: utf-8 -*-
"""Задание_1_со_звездочкой.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRz5xDK31-nD0UYYcEHAkgRRqo1oOxuN
"""

a = [42, 98, 8, 39, 64, 35, 71, 10, 50, 68, 91, 38, 69, 14, 88, 98, 89, 79, 44, 37, 2, 64, 19, 76, 91, 49, 88, 10, 10, 6]
b = input()
c =[]

for i in a:
  if int(b) > i:
    c.append(i)
print(c)