# -*- coding: utf-8 -*-
"""Cards

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1erhr55knk6iouOlWs1vgkJxY2-AjuJpe
"""

class Card:
  def __init__(self, suit, number, weight):
    self.suit = suit
    self.number = number
    self.weight = weight

  def create_deck_card():
    suits = ['Бубы', 'Черви', 'Трефы', 'Пики']
    numbers = ['6', '7', '8', '9', '10', 'Валет', 'Дама', 'Король', 'Туз']
    weights = {'6': 6, '7': 7, '8': 8, '9': 9, '10': 10, 'Валет': 2, 'Дама': 3, 'Король': 4, 'Туз': 11}

    deck = [Card(suit, number, weights[number]) for suit in suits for number in numbers]
    return deck

  deck_card = create_deck_card()

  for card in deck_card:
    print(f'Масть: {card.suit}, Число: {card.number}, Вес: {card.weight}')