# -*- coding: utf-8 -*-
"""Ведерки.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dsC4PHMdj7_h4QjzMZ0yyoV6Vvaq0KF2
"""

# frontend ------------------------------------------
bucket_3l_list = [" ", " ", " "]
bucket_5l_list = [" ", " ", " ", " ", " "]
clear = "\b"*10000
clear2 ="\b"*20
front = """

    3l             5l
              _____________
              \{7}{7}{7}{7}{7}{7}{7}{7}{7}{7}{7}/
_________      \{6}{6}{6}{6}{6}{6}{6}{6}{6}/
\{2}{2}{2}{2}{2}{2}{2}/       \{5}{5}{5}{5}{5}{5}{5}/
 \{1}{1}{1}{1}{1}/         \{4}{4}{4}{4}{4}/
  \{0}{0}{0}/           \{3}{3}{3}/
   ¯¯¯             ¯¯¯
"""

# database ------------------------------------------
database = {
    'bucket_3l': 0,
    'bucket_5l': 0,
}

# backend -------------------------------------------
working = True

i = 0

while working:

    # --------------------------------------------------------------
    bucket_3l_list = (["@"] * database['bucket_3l'] + [" "] * 3)[:3]
    bucket_5l_list = (["@"] * database['bucket_5l'] + [" "] * 5)[:5]
    print(front.format(*(bucket_3l_list[:4] + bucket_5l_list)))
    if database['bucket_5l'] == 4:
      break
    cmd = input(">> ")
    # --------------------------------------------------------------



    if cmd == "fill_3l":
        i += 1
        database['bucket_3l'] = 3

    elif cmd == "pour_3l":
        i += 1
        database['bucket_3l'] = 0

    elif cmd == "pour_5l":
        i += 1
        database['bucket_5l'] = 0

    elif cmd == "fill_5l":
        i += 1
        database['bucket_5l'] = 5

    elif cmd == "exit":
        break

    elif cmd == "pour_from_5_to_3":
        i += 1
        if database['bucket_5l'] == 5 and database['bucket_3l'] == 1:
          database['bucket_3l'] = 3
          database['bucket_5l'] = 3
        elif database['bucket_5l'] == 2 and database['bucket_3l'] == 0:
          database['bucket_3l'] = 2
          database['bucket_5l'] = 0
        elif database['bucket_5l'] == 5 and database['bucket_3l'] == 0:
          database['bucket_3l'] = 3
          database['bucket_5l'] = 2
        elif database['bucket_5l'] == 1 and database['bucket_3l'] == 0:
          database['bucket_3l'] = 1
          database['bucket_5l'] = 0
        elif database['bucket_5l'] == 3 and database['bucket_3l'] == 0:
          database['bucket_3l'] = 3
          database['bucket_5l'] = 0
        elif database['bucket_5l'] == 5 and database['bucket_3l'] == 1:
          database['bucket_3l'] = 3
          database['bucket_5l'] = 3
        elif database['bucket_5l'] == 5 and database['bucket_3l'] == 2:
          database['bucket_5l'] = 4
          database['bucket_3l'] = 3


    elif cmd == "pour_from_3_to_5":
      i += 1
      if database['bucket_5l'] == 3 and database['bucket_3l'] == 3:
        database['bucket_5l'] = 5
        database['bucket_3l'] = 1
      elif database['bucket_3l'] == 3 and database['bucket_5l'] == 0:
        database['bucket_3l'] = 0
        database['bucket_5l'] = 3
      elif database['bucket_5l'] == 0 and database['bucket_3l'] == 1:
        database['bucket_5l'] = 1
        database['bucket_3l'] = 0
      elif database['bucket_5l'] == 1 and database['bucket_3l'] == 3:
        database['bucket_5l'] = 4
        database['bucket_3l'] = 0
      elif database['bucket_3l'] == 3 and database['bucket_5l'] == 2:
        database['bucket_3l'] = 0
        database['bucket_5l'] = 5
      elif database['bucket_3l'] == 2 and database['bucket_5l'] == 0:
        database['bucket_3l'] = 0
        database['bucket_5l'] = 2
    print(clear)
print(f'Moves: {i}')