# -*- coding: utf-8 -*-
"""База данных.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H-Ylxcai1b7YayojjcO011Nk-w0_RFwm
"""

# frontend --------------------------
info = """
USER:\t\t{}
LAST CMD:\t{}
"""

# database --------------------------
database = {
    "logins": [],
    "passwords": []
}

# session ---------------------------
current_user = 'anonimus'

# backend ---------------------------
working = True
cmd = "null"

while working:
    print(info.format(current_user, cmd))
    cmd = input(">> ")
    if cmd == "singin":
      login = input("login: ")
      password_1 = input("password: ")
      password_2 = input("repeat password: ")
      if password_1 != password_2 or login in database["logins"]:
          print('Невернo')
      else:
          database["logins"] += [login]
          database["passwords"] += [hash(password_1)]
    elif cmd == "login" and current_user != 'anonimus':
       print('Выйдите из системы')
    elif cmd == "login" and current_user == 'anonimus':
      login = input("login: ")
      password = input("password: ")
      if login in database["logins"] and \
      hash(password) in database["passwords"]:
        current_user = login
      else:
        print('Неверный логин или пароль')
    elif cmd == "log out":
        current_user = 'anonimus'
    else:
        working = False
print("WORK COMPLETED")