# -*- coding: utf-8 -*-
"""Факториал.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m2HST3uaJce_saEsBKOwNwZTq8UFvhqZ
"""

def fuctorial(arg):
    c = 1
    for i in range(2, arg + 1):
      c = c * i
    print(f'Факториал {arg} равняется {c}')

fuctorial(int(input('Введите число: ')))